### PR TITLE
Update wagmi to 0.6 and rainbowkit to 0.4.5

### PR DESCRIPTION
**Pull request by michaellyons**

### CODE REVIEW

**Comment by Geczy** [comment]
is that really all that was needed?

**Comment by Dhaiwat10** [comment]
I doubt it. There were some breaking API changes in the recent versions for wagmi that must be needing updates 🤔

**Comment by Geczy** [comment]
yeah i was ognna say...

**Comment by michaellyons** [comment]
It runs, and there's barebones code in this repo on main branch. Am I missing something on install? Repo fails to run w/o these changes, upgraded modules allows the blank slate to start up. I only got here 5 minutes ago lol

**Comment by arihantbansal** [comment]
It should work. The template didn't have any `wagmi` code. Just a `ConnectButton` component.

**Comment by Dhaiwat10** [comment]
It did require some more work. Closing this in favor of #17, thanks!

**Pull request closed without merging**
